06-02 20:06:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "CURRVAL" nicht gefunden
Column "CURRVAL" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (currval, 'a', 'b','c','d','e','f','g') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:237)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-02 20:06:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES ('a', 'b','c','d','e','f','g') [21002-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.command.dml.Insert.prepare(Insert.java:232)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-02 20:07:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (MY_TABLE_SEQ.CURRVAL ,[*] 'a', 'b','c','d','e','f','g') "; erwartet "identifier"
Syntax error in SQL statement "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (MY_TABLE_SEQ.CURRVAL ,[*] 'a', 'b','c','d','e','f','g') "; expected "identifier"; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (MY_TABLE_SEQ.currval , 'a', 'b','c','d','e','f','g') [42001-172]
06-02 20:11:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID.CURRVAL ,[*] 'a', 'b','c','d','e','f','g') "; erwartet "identifier"
Syntax error in SQL statement "INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID.CURRVAL ,[*] 'a', 'b','c','d','e','f','g') "; expected "identifier"; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID.currval , 'a', 'b','c','d','e','f','g') [42001-172]
06-02 20:14:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"
Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"; SQL statement:
ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME TO ID_SEQUENCE [42000-172]
06-02 20:14:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"
Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"; SQL statement:
ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME TO ID_SEQUENCE [42000-172]
06-02 20:14:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"
Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"; SQL statement:
ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME TO ID_SEQUENCE [42000-172]
06-02 20:14:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"
Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"; SQL statement:
ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME TO ID_SEQUENCE [42000-172]
06-02 20:15:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Index "SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE" nicht gefunden
Index "SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE" not found; SQL statement:
ALTER INDEX SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME TO ID_SEQUENCE [42112-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.schema.Schema.getIndex(Schema.java:435)
	at org.h2.command.Parser.parseAlterIndex(Parser.java:4375)
	at org.h2.command.Parser.parseAlter(Parser.java:4354)
	at org.h2.command.Parser.parsePrepared(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-02 20:15:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"
Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"; SQL statement:
ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME TO ID_SEQUENCE [42000-172]
06-02 20:16:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER SEQUENCE 'SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME'[*] TO 'ID_SEQUENCE'"; erwartet "identifier"
Syntax error in SQL statement "ALTER SEQUENCE 'SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME'[*] TO 'ID_SEQUENCE'"; expected "identifier"; SQL statement:
ALTER SEQUENCE 'SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME' TO 'ID_SEQUENCE' [42001-172]
06-02 20:17:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"
Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME[*] TO ID_SEQUENCE"; SQL statement:
ALTER SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE RENAME TO ID_SEQUENCE [42000-172]
06-02 20:20:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Sequenz "SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE" gehört zu einer Tabelle
Sequence "SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE" belongs to a table; SQL statement:
DROP SEQUENCE SYSTEM_SEQUENCE_2AD2CD24_9AB2_4222_87B9_4C9E73EF13BE [90082-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:50)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-02 20:21:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "CUSTOMER" nicht gefunden
Column "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , CUSTOMER PASSWORD ) VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42122-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseColumn(Parser.java:802)
	at org.h2.command.Parser.parseColumnList(Parser.java:787)
	at org.h2.command.Parser.parseInsert(Parser.java:975)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:425)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:167)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-02 20:24:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "DROP *"; erwartet "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"
Syntax error in SQL statement "DROP *"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
DROP * [42001-172]
06-02 20:26:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "CUSTOMER" nicht gefunden
Table "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) 

VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42102-172]
06-02 20:26:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "CUSTOMER" nicht gefunden
Table "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) 

VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42102-172]
06-02 20:26:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "CUSTOMER" nicht gefunden
Table "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) 

VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42102-172]
06-02 20:26:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "CUSTOMER" nicht gefunden
Table "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) 

VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42102-172]
06-02 20:26:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "CUSTOMER" nicht gefunden
Table "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) 

VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42102-172]
06-02 20:26:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "CUSTOMER" nicht gefunden
Table "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) 

VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42102-172]
06-02 20:26:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "CUSTOMER" nicht gefunden
Table "CUSTOMER" not found; SQL statement:
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME , ADDRESS , TELNO , MAILADDRESS , COMPANY , PASSWORD ) VALUES (ID_CUSTOMER_SEQ.currval , 'a', 'b','c','d','e','f','g') [42102-172]
06-02 22:01:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "Customer" nicht gefunden
Table "Customer" not found; SQL statement:
UPDATE "Customer" SET  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?; [42102-168]
06-02 22:01:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "Customer" nicht gefunden
Table "Customer" not found; SQL statement:
UPDATE "Customer" SET  AND ID = ? AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?; [42102-168]
06-02 22:03:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE CUSTOMER SET  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.CustomerDAO.UpdateCustomer(CustomerDAO.java:313)
	at bakewell.db.CustomerDAOTest.testCustomerDAOUpdate_ShouldWork(CustomerDAOTest.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:03:10 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE CUSTOMER SET  AND ID = ? AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.CustomerDAO.UpdateCustomer(CustomerDAO.java:313)
	at bakewell.db.CustomerDAOTest.testCustomerDAOUpdate_ShouldFail(CustomerDAOTest.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:04:57 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE CUSTOMER SET  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.CustomerDAO.UpdateCustomer(CustomerDAO.java:313)
	at bakewell.db.CustomerDAOTest.testCustomerDAOUpdate_ShouldWork(CustomerDAOTest.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:05:00 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "UPDATE CUSTOMER SET ID = ? AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE[*] 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?;"; erwartet "ALL, ANY, SOME, SELECT, FROM"
Syntax error in SQL statement "UPDATE CUSTOMER SET ID = ? AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE[*] 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?;"; expected "ALL, ANY, SOME, SELECT, FROM"; SQL statement:
UPDATE CUSTOMER SET ID = ? AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD =  WHERE 1=1  AND FIRSTNAME = ? AND LASTNAME = ? AND ADDRESS = ? AND TELNO = ? AND MAILADDRESS = ? AND COMPANY = ? AND PASSWORD = ?; [42001-168]
06-02 22:10:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "UPDATE CUSTOMER SET  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  FIRSTNAME[*] = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ?,;"
Syntax error in SQL statement "UPDATE CUSTOMER SET  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  FIRSTNAME[*] = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ?,;"; SQL statement:
UPDATE CUSTOMER SET  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ?,; [42000-168]
06-02 22:10:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "UPDATE CUSTOMER SET  ID = ?, FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  FIRSTNAME[*] = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ?,;"
Syntax error in SQL statement "UPDATE CUSTOMER SET  ID = ?, FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  FIRSTNAME[*] = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ?,;"; SQL statement:
UPDATE CUSTOMER SET  ID = ?, FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ?,; [42000-168]
06-02 22:11:39 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "UPDATE CUSTOMER SET  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  AND FIRSTNAME = ?,[*] AND LASTNAME = ?, AND ADDRESS = ?, AND TELNO = ?, AND MAILADDRESS = ?, AND COMPANY = ?, AND PASSWORD = ?,;"
Syntax error in SQL statement "UPDATE CUSTOMER SET  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  AND FIRSTNAME = ?,[*] AND LASTNAME = ?, AND ADDRESS = ?, AND TELNO = ?, AND MAILADDRESS = ?, AND COMPANY = ?, AND PASSWORD = ?,;"; SQL statement:
UPDATE CUSTOMER SET  FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  AND FIRSTNAME = ?, AND LASTNAME = ?, AND ADDRESS = ?, AND TELNO = ?, AND MAILADDRESS = ?, AND COMPANY = ?, AND PASSWORD = ?,; [42000-168]
06-02 22:11:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "UPDATE CUSTOMER SET  ID = ?, FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  AND FIRSTNAME = ?,[*] AND LASTNAME = ?, AND ADDRESS = ?, AND TELNO = ?, AND MAILADDRESS = ?, AND COMPANY = ?, AND PASSWORD = ?,;"
Syntax error in SQL statement "UPDATE CUSTOMER SET  ID = ?, FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  AND FIRSTNAME = ?,[*] AND LASTNAME = ?, AND ADDRESS = ?, AND TELNO = ?, AND MAILADDRESS = ?, AND COMPANY = ?, AND PASSWORD = ?,;"; SQL statement:
UPDATE CUSTOMER SET  ID = ?, FIRSTNAME = ?, LASTNAME = ?, ADDRESS = ?, TELNO = ?, MAILADDRESS = ?, COMPANY = ?, PASSWORD = ? WHERE 1=1  AND FIRSTNAME = ?, AND LASTNAME = ?, AND ADDRESS = ?, AND TELNO = ?, AND MAILADDRESS = ?, AND COMPANY = ?, AND PASSWORD = ?,; [42000-168]
06-02 22:45:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOInsert_ShouldWork(IngredientDAOTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAODelete_ShouldWork(IngredientDAOTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAODelete_ShouldWork(IngredientDAOTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAODelete_ShouldFail(IngredientDAOTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[13]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldWork(IngredientDAOTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Feld "AMOUNT" nicht gefunden
Column "AMOUNT" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND AMOUNT = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldWork(IngredientDAOTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[15]: exception
org.h2.jdbc.JdbcSQLException: Feld "FAT" nicht gefunden
Column "FAT" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND FAT = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldWork(IngredientDAOTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Feld "SUGAR" nicht gefunden
Column "SUGAR" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND SUGAR = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldWork(IngredientDAOTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: Feld "CALORIES" nicht gefunden
Column "CALORIES" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldWork(IngredientDAOTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldFail(IngredientDAOTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[21]: exception
org.h2.jdbc.JdbcSQLException: Feld "AMOUNT" nicht gefunden
Column "AMOUNT" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND AMOUNT = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldFail(IngredientDAOTest.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:40 jdbc[22]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-168]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:172)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at bakewell.db.IngredientDAO.openConnection(IngredientDAO.java:72)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:199)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldFail(IngredientDAOTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 33 more
06-02 22:45:40 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Feld "FAT" nicht gefunden
Column "FAT" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND FAT = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldFail(IngredientDAOTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "SUGAR" nicht gefunden
Column "SUGAR" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND SUGAR = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldFail(IngredientDAOTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:41 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "CALORIES" nicht gefunden
Column "CALORIES" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOSelect_ShouldFail(IngredientDAOTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE CUSTOMER SET  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:45:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldFail(IngredientDAOTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:47:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT * FROM CUSTOMER WHERE 1=1 AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:127)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.selectIngredient(IngredientDAO.java:220)
	at bakewell.db.IngredientDAOTest.testIngredientDAOInsert_ShouldWork(IngredientDAOTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:50:32 jdbc[27]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:50:32 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND ID = ? AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldFail(IngredientDAOTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:57:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 22:57:48 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND ID = ? AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldFail(IngredientDAOTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 23:00:39 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 23:00:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Das Objekt wurde bereits geschlossen
The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:262)
	at bakewell.db.IngredientDAO.deleteIngredient(IngredientDAO.java:168)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 23:00:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 23:01:00 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND ID = ? AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldFail(IngredientDAOTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 23:01:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldWork(IngredientDAOTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-02 23:01:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "AND" nicht gefunden
Column "AND" not found; SQL statement:
UPDATE INGREDIENT SET  AND ID = ? AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES =  WHERE 1=1  AND NAME = ? AND AMOUNT = ? AND FAT = ? AND SUGAR = ? AND CALORIES = ?; [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:605)
	at org.h2.command.Parser.readTableColumn(Parser.java:655)
	at org.h2.command.Parser.parseUpdate(Parser.java:689)
	at org.h2.command.Parser.parsePrepared(Parser.java:427)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at bakewell.db.IngredientDAO.UpdateIngredient(IngredientDAO.java:295)
	at bakewell.db.IngredientDAOTest.testIngredientDAOUpdate_ShouldFail(IngredientDAOTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "RECIPE" nicht gefunden
Table "RECIPE" not found; SQL statement:
DROP TABLE RECIPE [42102-172]
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PRODUCT" nicht gefunden
Table "PRODUCT" not found; SQL statement:
DROP TABLE PRODUCT [42102-172]
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "INGREDIENT2RECIPE" nicht gefunden
Table "INGREDIENT2RECIPE" not found; SQL statement:
DROP TABLE INGREDIENT2RECIPE [42102-172]
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "GDAREFERENCE" nicht gefunden
Table "GDAREFERENCE" not found; SQL statement:
DROP TABLE GDAREFERENCE [42102-172]
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequenz "ID_PRODUCT_SEQ" nicht gefunden
Sequence "ID_PRODUCT_SEQ" not found; SQL statement:
DROP SEQUENCE ID_PRODUCT_SEQ [90036-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequenz "ID_RECIPE_SEQ" nicht gefunden
Sequence "ID_RECIPE_SEQ" not found; SQL statement:
DROP SEQUENCE ID_RECIPE_SEQ [90036-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequenz "ID_INGREDIENT2RECIPE_SEQ" nicht gefunden
Sequence "ID_INGREDIENT2RECIPE_SEQ" not found; SQL statement:
DROP SEQUENCE ID_INGREDIENT2RECIPE_SEQ [90036-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
06-08 18:23:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequenz "ID_GDAREFERENCE_SEQ" nicht gefunden
Sequence "ID_GDAREFERENCE_SEQ" not found; SQL statement:
DROP SEQUENCE ID_GDAREFERENCE_SEQ [90036-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1316)
	at org.h2.server.web.WebApp.query(WebApp.java:1005)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebApp$1.next(WebApp.java:954)
	at org.h2.server.web.WebThread.process(WebThread.java:167)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
